### ISSUE TITLE
Relative Path - import path wrong

### ISSUE THREAD

**Issue by D1no** [zucska/extract-component#3]
I have the following structure

```bash
app/
    component/
        componentName/
            index.js
    container
    scene
        sceneName
            index.js // created component is referenced as "../componentName" <- one level too low
```

When I extract a component part from a scene, the component is correctly created but referenced one level too low (it should be "../../component/componentName").

### Allow a fixed import symbol as path replacement 
We also use `package.json` to make imports easier. It would be great if it was possible to define the component import path manually. For example `"@component"`.

We have i.e. a `package.json` in the component folder which makes it possible to import components from anywhere ([read it here](https://blog.callstack.io/a-cure-for-relative-requires-in-react-native-2b263cecf0f6)).
```js
// app/component/package.json
{
  "name": "@component"
}
```

now you can import your component from anywhere in your code via the name of the `package.json` (thats how the normal node.js module resolution works)
```js
// app/some/where/inside/the/code/index.js
import Button from "@component/componentName";
(...)
import Welcome from "@scene/welcome";
import CenterView from "@container/centerView";
```

Being able to define a fixed import path symbol (i.e. `"@component"`) would make your extension very useful.

**Comment by D1no** [comment]
Why was this closed?

**Comment by D1no** [comment]
@zucska ?

**Comment by zucska** [comment]
The requested featured has been implemented in the latest update.
